### ISSUE TITLE
Switch to phpcsstandards/codesniffer 

### ISSUE THREAD

**Issue by brunob** [JamesRezo/spip-coding-standards#2]
> Note: I would recommend waiting to make the switch until the 3.8.0 release has been tagged. Watch releases on the [new repo](https://github.com/PHPCSStandards/PHP_CodeSniffer) to automatically get notified of this. The changelog will contain the relevant information for making the switch.

Ref https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

**Comment by brunob** [comment]
Du nouveau :

> Yes, for those few users who didn't heed my warning to wait with switching until there had been a release, those would need to switch back, but that's a much smaller number than all the Composer users having to switch and it will prevent a world of potential issues with vendor/bin files if people would change the package name, but would not update to the latest tag, so let's.

https://github.com/squizlabs/PHP_CodeSniffer/issues/3932#issuecomment-1842531678

Bref, il faut revert d66d6320f15ffe5824bf196e6c70372e86c51a37 tu as été trop rapide :p

**Comment by jrfnl** [comment]
Thank you for your support and your enthousiasm embracing the take-over of the PHP_CodeSniffer package.

In contrast to earlier information, arrangements are now being made to allow the package to continue under its original name on Packagist. The commit (in the new repo) to rename the package [has been reverted](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/135).

Sorry for the confusion and thank you for understanding. I hope you'll enjoy the 3.8.0 release, which I expect to release this Friday.

**Comment by brunob** [comment]
ping @JamesRezo on devait pas revert ça ?

**Comment by JamesRezo** [comment]
Ce soir si j'ai du temps, mon mignon 💋

**Comment by JamesRezo** [comment]
Done ✅ 🚀
